#!/bin/bash
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update ingress-nginx
helm upgrade --install \
  ingress-controller ingress-nginx/ingress-nginx \
  --create-namespace \
  --namespace ingress-controller
