#!/bin/bash
helm repo add jetstack https://charts.jetstack.io
helm repo update jetstack
helm upgrade --install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --set prometheus.enabled=false \
  --set installCRDs=true
#  --version v1.9.1 \

kubectl create -f configs
